table Fact_Sales
	lineageTag: 8e532e3e-330e-49a9-945b-aff10e95e684

	measure 'MoM Sales Growth' =
			VAR CurrentSales =
			    SUM(Fact_Sales[sales_amount])
			VAR PreviousMonthSales =
			    CALCULATE(
			        SUM(Fact_Sales[sales_amount]),
			        DATEADD(Dim_Date[date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(CurrentSales - PreviousMonthSales, PreviousMonthSales)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3cc89a06-5020-4bac-9505-33622e088886

	measure 'Running Total Sales' =
			CALCULATE (
			    SUM ( Fact_Sales[sales_amount] ),
			    FILTER (
			        ALLSELECTED ( Dim_Date[date] ),
			        Dim_Date[date] <= MAX ( Dim_Date[date] )
			    )
			)

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 101bc188-4478-4480-bb5e-6c5c52fff21e
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2027285a-b9f4-4610-beef-2062fb549372
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: fc3603a4-a862-4135-8440-bdf623b9fd7e
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: e763d7c1-c18d-4786-86b7-4ae0ac04fc4f
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 9cd4a1d9-e43a-47be-bf25-ac1f0fbe01d8
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 42101fec-01d8-47bd-8e91-eb6f40fbd741
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 35962b2a-6784-4b23-ba49-48553e6c7304
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 7f2626b5-e4e1-499d-887d-b483d472eaa9
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 6ac22a85-5b59-4b1c-8a65-663daeffc40f
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\raaru\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

